// Posts actions
export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_RESPONSE = 'FETCH_POSTS_RESPONSE';

// Post actions
export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POST_RESPONSE = 'FETCH_POST_RESPONSE';
